#include"a.h" // ngn/k, (c) 2019-2022 ngn, GNU AGPLv3 - https://codeberg.org/ngn/k/raw/branch/master/LICENSE
#define hg(T) (HD/SZ(T))
S N abB(L a,OV*RE b0,V*RE r0,Nn)_(I g=hg(B);O B*b=b0;B*r=r0;LI(b)LI(r)Li=0;W(i<n,B v[g],o=0;j(g,B u=a+b[j];o|=(a^u)&(b[j]^u);v[j]=u)P(o>>SZ(B)*8-1,i)Mc(r,v,HD);i+=g;b+=g;r+=g)i)
S N ahH(L a,OV*RE b0,V*RE r0,Nn)_(I g=hg(H);O H*b=b0;H*r=r0;LI(b)LI(r)Li=0;W(i<n,H v[g],o=0;j(g,H u=a+b[j];o|=(a^u)&(b[j]^u);v[j]=u)P(o>>SZ(H)*8-1,i)Mc(r,v,HD);i+=g;b+=g;r+=g)i)
S N aiI(L a,OV*RE b0,V*RE r0,Nn)_(I g=hg(I);O I*b=b0;I*r=r0;LI(b)LI(r)Li=0;W(i<n,I v[g],o=0;j(g,I u=a+b[j];o|=(a^u)&(b[j]^u);v[j]=u)P(o>>SZ(I)*8-1,i)Mc(r,v,HD);i+=g;b+=g;r+=g)i)
S N alL(L a,OV*RE b0,V*RE r0,Nn)_(O L*b=b0;L*r=r0;LI(b)LI(r)i(PD(n,b),r[i]=a+b[i])n)
S N mbB(L a,OV*RE b0,V*RE r0,Nn)_(I g=hg(B);O B*b=b0;B*r=r0;LI(b)LI(r)Li=0;W(i<n,H v[g];j(g,v[j]=a*(H)b[j])j(g,P(v[j]-(B)v[j],i))j(g,r[j]=v[j])i+=g;b+=g;r+=g)i)
S N mhH(L a,OV*RE b0,V*RE r0,Nn)_(I g=hg(H);O H*b=b0;H*r=r0;LI(b)LI(r)Li=0;W(i<n,I v[g];j(g,v[j]=a*(I)b[j])j(g,P(v[j]-(H)v[j],i))j(g,r[j]=v[j])i+=g;b+=g;r+=g)i)
S N miI(L a,OV*RE b0,V*RE r0,Nn)_(I g=hg(I);O I*b=b0;I*r=r0;LI(b)LI(r)Li=0;W(i<n,L v[g];j(g,v[j]=a*(L)b[j])j(g,P(v[j]-(I)v[j],i))j(g,r[j]=v[j])i+=g;b+=g;r+=g)i)
S N mlL(L a,OV*RE b0,V*RE r0,Nn)_(O L*b=b0;L*r=r0;LI(b)LI(r)i(PD(n,b),r[i]=a*b[i])n)
S N aBB(OV*RE a0,OV*RE b0,V*RE r0,Nn)_(I g=hg(B);O B*a=a0,*b=b0;B*r=r0;LI(b)LI(r)LI(a)Li=0;W(i<n,B v[g],o=0;j(g,B u=a[j]+b[j];o|=(a[j]^u)&(b[j]^u);v[j]=u)P(o>>SZ(B)*8-1,i)Mc(r,v,HD);i+=g;a+=g;b+=g;r+=g)i)
S N aHH(OV*RE a0,OV*RE b0,V*RE r0,Nn)_(I g=hg(H);O H*a=a0,*b=b0;H*r=r0;LI(b)LI(r)LI(a)Li=0;W(i<n,H v[g],o=0;j(g,H u=a[j]+b[j];o|=(a[j]^u)&(b[j]^u);v[j]=u)P(o>>SZ(H)*8-1,i)Mc(r,v,HD);i+=g;a+=g;b+=g;r+=g)i)
S N aII(OV*RE a0,OV*RE b0,V*RE r0,Nn)_(I g=hg(I);O I*a=a0,*b=b0;I*r=r0;LI(b)LI(r)LI(a)Li=0;W(i<n,I v[g],o=0;j(g,I u=a[j]+b[j];o|=(a[j]^u)&(b[j]^u);v[j]=u)P(o>>SZ(I)*8-1,i)Mc(r,v,HD);i+=g;a+=g;b+=g;r+=g)i)
S N aLL(OV*RE a0,OV*RE b0,V*RE r0,Nn)_(O L*a=a0,*b=b0;L*r=r0;LI(b)LI(r)i(PD(n,a),r[i]=a[i]+b[i])n)
S N mBB(OV*RE a0,OV*RE b0,V*RE r0,Nn)_(I g=hg(B);O B*a=a0,*b=b0;B*r=r0;LI(b)LI(r)LI(a)Li=0;W(i<n,H v[g];j(g,v[j]=a[j]*(H)b[j])j(g,P(v[j]-(B)v[j],i))j(g,r[j]=v[j])i+=g;a+=g;b+=g;r+=g)i)
S N mHH(OV*RE a0,OV*RE b0,V*RE r0,Nn)_(I g=hg(H);O H*a=a0,*b=b0;H*r=r0;LI(b)LI(r)LI(a)Li=0;W(i<n,I v[g];j(g,v[j]=a[j]*(I)b[j])j(g,P(v[j]-(H)v[j],i))j(g,r[j]=v[j])i+=g;a+=g;b+=g;r+=g)i)
S N mII(OV*RE a0,OV*RE b0,V*RE r0,Nn)_(I g=hg(I);O I*a=a0,*b=b0;I*r=r0;LI(b)LI(r)LI(a)Li=0;W(i<n,L v[g];j(g,v[j]=a[j]*(L)b[j])j(g,P(v[j]-(I)v[j],i))j(g,r[j]=v[j])i+=g;a+=g;b+=g;r+=g)i)
S N mLL(OV*RE a0,OV*RE b0,V*RE r0,Nn)_(O L*a=a0,*b=b0;L*r=r0;LI(b)LI(r)i(PD(n,a),r[i]=a[i]*b[i])n)

S A adm(Ax,Ay,Iv/*01v*/)_(XYmMA(e2f(v?mul:add,x,y))Ik=2*xtT+ytT;
 P(!k,P(xti&&yti,az(v?xv*(L)yv:xv+(L)yv))P(xtzc&&ytzc,Lm=gl_(x),n=gl(y);az(v?m*n:m+n))x=Ny(cF(xR));y=Nx(cF(y));F a=gf(x),b=gf(y);af(v?a*b:a+b))P(k==2,y(adm(y,xR,v)))P(k==3&&xn-yn,el1(y))
 P(xtfF||ytF,P(!xtfF,x=Ny(cF(xR));x(adm(x,y,v)))P(!ytF,adm(x,Ny(cF(y)),v))
  Az=yr-1?aF(yn):y;Nn=PD(zn,zF);I(k==1,F a=*xF;I(v,i(n,zf=a*yf))E(i(n,zf=a+yf)))J(v,i(n,zf=xf*yf))E(i(n,zf=xf+yf))y-z?y(z):z)
 XcC(y(adm(y,cB(xR),v)))YC(adm(x,cB(y),v))P(!xtzZ||!ytZ,et1(y))
 P(k==1,L a=gl_(x);Ct=max(tZ(a),yt);y=N(cT[t](y));Nn=yn,m=0;Az=yr-1?an(yt,n):y;
  W(1,N l=m*zW;m+=T(&abB,ahH,aiI,alL,mbB,mhH,miI,mlL)[4*v|yt-tB](a,yV+l*(y==z),zV+l,n-m);B(m>=n)I(y-z,y=wdn(y,m,n,n-m);z=wdn(z,0,m,n))E(y=z=wdn(z,0,n,n)))y-z?y(z):z)
 Q(k==3);I w=max(xw,yw);P(xw-w,x=cT[tB+w](xR);x(adm(x,y,v)))y=cT[tB+w](y);Nn=yn;Az=yr-1?an(yt,n):y;Nm=0;I ox=0;
 W(1,N l=m<<w;m+=T(&aBB,aHH,aII,aLL,mBB,mHH,mII,mLL)[4*v|w](xV,yV+l*(y==z),zV+l,n-m);B(m>=n)w++;x=wdn(ox?x:xR,m,n,n-m);ox=1;I(y-z,y=wdn(y,m,n,n-m);z=wdn(z,0,m,n))E(y=z=wdn(z,0,n,n)))
 I(ox,x(0))y-z?y(z):z)

A2(dex,y)A2(add,adm(x,y,0))A2(sub,add(x,N(neg(y))))A2(mul,adm(x,y,1))
A2(dvd,XYmMA(e2f(dvd,x,y))x=Ny(cF(xR));y=Nx(cF(y));Xf(Fv=gf(x);Yf(af(v/gf(y)))Az=yr==1?y:aF(yn);i(yn,zf=v/yf)y-z?y(z):z)Yf(Fv=gf(y);Az=xr==1?x:aF(xn);i(xn,zf=xf/v)x-z?x(z):z)
 P(xn-yn,el2(x,y))Az=xr==1?x:yr==1?y:aF(xn);i(xn,zf=xf/yf)x==z?y(z):y==z?x(z):x(y(z)))
A2(mod,YmMA(e2f(mod,x,y))YfF(Ln=gl_(x);P(!n,y)P(n<0,en1(y))K2("{y-x*(-x)!`i$y}",x,y))Yzc(fir(N(mod(x,enl(y)))))YC(mod(x,cB(y)))
 YZ(Lm=gl_(x);P(!m,y)P(m<0,m=-m;Az=an(yt,yn);S4(yw,i(zn,Cv=yb;zb=v<0?-1-~v/m:v/m),i(zn,Hv=yh;zh=v<0?-1-~v/m:v/m),i(zn,Iv=yi;zi=v<0?-1-~v/m:v/m),i(zn,Lv=yl;zl=v<0?-1-~v/m:v/m))y(z))
  P(m&m-1,Az=an(tZ(m),yn);I wy=yw;S4(zw,i(zn,zb=(iw(y,wy,i)%m+m)%m),i(zn,zh=(iw(y,wy,i)%m+m)%m),i(zn,zi=(iw(y,wy,i)%m+m)%m),i(zn,zl=(iw(y,wy,i)%m+m)%m))y(z))
  m--;I t=tZ(m),w=t-tB;y=mut(N(cT[t](y)));i(3-w,m|=m<<(8<<w+i))L*p=yV;i((yn<<w)+31>>5,j(4,*p++&=m))y)ed1(y))
S ALA(ext/*n1*/,XMT(x)rsz(n,xtm?enl(x):x))A2(dct,/*01*/P(rnk(x)<0,ed1(y))x=ext(yN,xR);y=ext(xN,y);(xN-yN?el2:am)(x,y))A2(bng,Xzc(mod(x,y))dct(x,y))
S C tZx(Ax)_(Ct=TX[xt];P(t,t)Xl(tZ(gl_(x)))tZ(xv))C sup(A*p,A*q)_(Ax=*p,y=*q;Ct=max(tZx(x),tZx(y));*p=x=Ny(cT[t](x));*q=y=Nx(cT[t](y));t)
S A mmm(Ax,Ay,A2 f)_(XYmMA(e2f(f,x,y))P(xtfF||ytfF,x=of1(Ny(cF(xR)));y=of1(Nx(cF(y)));x(of0(f(x,y))))
 Ik=xtT<<1|ytT;P(!k,P(xtzc&&ytzc,Lv=gl_(x),w=gl(y);az(f==mnm?min(v,w):max(v,w)))et1(y))P(k==2,y(f(y,xR)))P(k==3&&xn-yn,el1(y))
 xR;N(sup(&x,&y));Ct=TT[k?min(xt,yt):max(xt,yt)];Nn=k-1?xn:yn;Az=yt==t&&yr==1?y:an(t,n);
 I(k==1,Lv=gl_(x);I(f==mnm,S4(zw,i(n,zb=min( v,yb)),i(n,zh=min( v,yh)),i(n,zi=min( v,yi)),i(n,zl=min( v,yl))))
                  E(       S4(zw,i(n,zb=max( v,yb)),i(n,zh=max( v,yh)),i(n,zi=max( v,yi)),i(n,zl=max( v,yl)))))
 E(Q(k==3);       I(f==mnm,S4(zw,i(n,zb=min(xb,yb)),i(n,zh=min(xh,yh)),i(n,zi=min(xi,yi)),i(n,zl=min(xl,yl))))
                  E(       S4(zw,i(n,zb=max(xb,yb)),i(n,zh=max(xh,yh)),i(n,zi=max(xi,yi)),i(n,zl=max(xl,yl)))))x(y-z?y(z):z))
A2(mnm,mmm(x,y,mnm))A2(mxm,mmm(x,y,mxm))
A2(ltn,P((1<<xt|1<<yt)&(1<<tm|1<<tM|1<<tA|1<<tS),e2f(ltn,x,y))
 Ik=xtT<<1|ytT;P(!k,P(xtzc&&ytzc,ai(gl_(x)<gl(y)))P(xtzfc&&ytzfc,x=Ny(cF(xR));y=Nx(cF(y));ai(qf(gf(x),gf(y))<0))P(xts&&yts,y(ai(qA(x,y)<0)))et1(y))
 P(k==3&&xn-yn,el1(y))xR;N(sup(&x,&y));XfF(x=of1(x);x(ltn(x,of1(y))))P(k==2,y=az(gl(y)-1);not(N(y(ltn(y,x)))))Nn=k-1?xn:yn;Az=aB(n);
 I(k==1,Lv=gl_(x);S4(yw,i(n,zb=v<yb),i(n,zb=v<yh),i(n,zb=v<yi),i(n,zb=v<yl)))E(Q(k==3);S4(xw,i(n,zb=xb<yb),i(n,zb=xh<yh),i(n,zb=xi<yi),i(n,zb=xl<yl)))x(y(z)))
A2(gtn,y(ltn(y,xR)))
A2(eql,XYmMA(e2f(eql,x,y))P(xtsS-ytsS,et1(y))P(xtsS,x=AT(xt+ti-ts,mut(xR));x(eql(x,AT(yt+ti-ts,mut(y)))))
 Ik=xtT<<1|ytT;P(!k,P(xtzc&&ytzc,ai(gl_(x)==gl(y)))P(xtf||ytf,x=Ny(cF(xR));y=Nx(cF(y));ai(gl(x)==gl(y)))et1(y))P(k==2,y(eql(y,xR)))P(k==3&&xn-yn,el1(y))
 xR;N(sup(&x,&y));Ct=TT[k?min(xt,yt):max(xt,yt)];I w=Tz[t];Nn=k-1?xn:yn;Az=aB(n);
 I(k==1,S4(w,{Cv=xv;i(n,zb=v==yb)},{Hv=xv;i(n,zb=v==yh)},{Iv=xv;i(n,zb=v==yi)},{Lv=gl_(x);i(n,zb=v==yl)}))
 E(Q(k==3);S4(w,i(n,zb=xb==yb),i(n,zb=xh==yh),i(n,zb=xi==yi),i(n,zb=xl==yl)))x(y(z)))
