#include"a.h" // ngn/k, (c) 2019-2023 ngn, GNU AGPLv3 - https://codeberg.org/ngn/k/raw/branch/master/LICENSE
S A1(sam,x)V_;T_;I _K(Ax/*0*/)_(X(R2(tu,tw,1)Rv(2)Rx(x>>48&7)R4(to,tp,tq,tr,xk))0)
X1(mkn,RmMA(e1f(mkn,x))Rt(x(_R(cn[xt])))R_(x(rsz(xN,_R(cn[xt])))))
A1(iei,/*0*/xtv&&xv<10u?"\4\0\0\1\1\2\2\3\3\2"[xv]:4)
Y2(iex,/*01*/RmMA(r2f(iex,x,y))RT_A(rsz(yN,iex(x,fir(y))))Rs(as(0))Rc(ac("\0\1\x7f\x80 "[iei(x)]))Rf(y(af(A(0.,1.,WF,-WF,NF)[iei(x)])))R_(y(az(G(0ll,1,WL,-WL,NL)[iei(x)]))))
A2(ie,/*00*/P(x==CAT,_R(ce[ce[yt]?yt:tA]))iex(x,fir(yR)))
AX(prj,XmMA(x8(a,n))Ik=MAX(n,xK);i(n,k-=a[i]!=PLH)x=(xtp?val:aA1)(xR);Ii=0,j=1;W(i<n&&j<xn,I(xA[j]==PLH,xA[j]=a[i++])j++)W(i<n,xq(a[i++]))P(xn>9,ez1(x))AT(tp,AK(k,x)))
S A iM(Ax,Li,AAL*f)_(Q(xtM);Ay=xy,z=aA(yn);Q(ytA);j(zn|!zn,zA[j]=f(yA[j],i))am(_R(xx),sqz(z)))
AAL(ii,/*0*/X(RA(_R(xa))RC(ac(xc))RG(ai(xg))RH(ai(xh))RI(ai(xi))RL(al(xl))RF(af(xf))RS(as(xi))Rm(ii(xy,i))RM(iM(x,i,ii))RE(az(*xL+i))R_(xR))0)
AAL(io,/*0*/X(RE(IN(i,xL[1]-*xL)?az(*xL+i):_R(cn[tl]))RT_E(IN(i,xn)?ii(x,i):xn?mkn(ii(x,0)):xtA?_R(xx):_R(cn[xt]))Rt(xR)Rm(io(xy,i))RM(iM(x,i,io)))0)
A1(fir,x(io(x,0)))A1(las,x(io(x,xN-1)))
SN I o(O UI*a,Nm,Nn)_(UI v=0;i(n,v=MAX(v,a[i]))v>=m)
SN V iG(V*RES a,Nm,O UI*RES b,V*RES c,Nn){G*p=a;G*r=c;i(n,r[i]=p[b[i]])}
SN V iH(V*RES a,Nm,O UI*RES b,V*RES c,Nn){H*p=a;H*r=c;i(n,r[i]=p[b[i]])}
SN V iI(V*RES a,Nm,O UI*RES b,V*RES c,Nn){I*p=a;I*r=c;i(n,r[i]=p[b[i]])}
SN V iC(V*RES a,Nm,O UI*RES b,V*RES c,Nn){C*p=a;C*r=c;i(n+31&-32,r[i]=b[i]<m?p[b[i]]:32)}
SN V iS(V*RES a,Nm,O UI*RES b,V*RES c,Nn){I*p=a;I*r=c;i(n+7&-8,r[i]=b[i]<m?p[b[i]]: 0)}
SN V jG(V*RES a,Nm,O UI*RES b,V*RES c,Nn){G*p=a;L*r=c;i(n+3&-4,r[i]=b[i]<m?p[b[i]]:NL)}
SN V jH(V*RES a,Nm,O UI*RES b,V*RES c,Nn){H*p=a;L*r=c;i(n+3&-4,r[i]=b[i]<m?p[b[i]]:NL)}
SN V jI(V*RES a,Nm,O UI*RES b,V*RES c,Nn){I*p=a;L*r=c;i(n+3&-4,r[i]=b[i]<m?p[b[i]]:NL)}
SN V jv(V*RES a,Nm,O UI*RES b,V*RES c,Nn,Lv){L*p=a;L*r=c;i(n+3&-4,r[i]=b[i]<m?p[b[i]]:v)}
SN V jL(V*RES a,Nm,O UI*RES b,V*RES c,Nn){jv(a,m,b,c,n,NL);}
SN V jF(V*RES a,Nm,O UI*RES b,V*RES c,Nn){jv(a,m,b,c,n,NFL);}
A2(i1,/*01*/P(y==PLH||y==au,xR)
 X(Rt(y(xR))RE(x=gZ(xR);x(i1(x,y)))Rm(i1(xy,N(fnd(xx,y))))
  RM(Y(RsS(x=flp(xR);x(i1(x,y)))RA(r2(AP1,x,y))RmM(Az=kv(&y);am(y,Ny(i1(x,z))))R_(I d=ytmt;y=N(l2f(i1,xy,y));(d?am:aM)(_R(xx),y)))0))
 Y(Rzc(io(x,gl(y)))RmM(Az=kv(&y);am(y,Ny(i1(x,z))))RA(r2(AP1,x,y))RE(Li=*yL,j=yL[1];P(0<=i&&i<j&&j<xN,y(0);slc(x,i,j))i1(x,gZ(y)))R3(tG,tH,tC,i1(x,cI(y)))R_(et1(y))
  RL(Nm=xn;Az=aI(yn);My(i(yn+3&-4,Lv=yl;zi=v|-(v!=(I)v)))i1(x,z))
  RI(Nn=yn;XA(Az=aA(n);i(n|!n,za=io(x,yi))y(0);I(!zn,zx=mkn(zx))sqz(z))
   Ct=xt;Ik=t-tG<3u&&o(yV,xn,yn);Az=an(n,k?tL:t);My(G(&iG,iH,iI,jL,jF,iC,iS,jG,jH,jI)[7*k+t-tG](xV,xn,yV,zV,n))z))0)
S A3(i2,/*001*/Cb=ytT||y==PLH||y==au;x=Nz(i1(x,yR));P(!b,x(x1(z)))x(l2f(dot,x,aA1(z))))
S AX(i8,Ay=*a;P(n==1,i1(x,y))P(n==2,y(_2(x,y,a[1])))a++;n--;Cb=ytT||y==PLH||y==au;x=i1(x,y);P(!x,mrn(n,a);x)P(!b,x(i8(x,a,n)))x(l2f(dot,x,aV(tA,n,a))))
L iw(Ax/*0*/,I w,Li)_(S4(w,_(xg),_(xh),_(xi),_(xl))0)
S A1(qa,Ay=oA;Q*p=argv;W(*p,yq(aCz(*p++)))y(y1(x)))
S A1(qe,Ay=oS,z=oA;Q*e=env;W(*e,Qp=*e++,q=strchrnul(p,'=');yq(cS(aCm(p,q)));zq(aCz(q+!!*q)))y=am(y,z);x-au?x(x1(y)):y)
S A1(qx,exit(xtz?gl(x):1);0)
S X1(qjs,RC(Cb[4096];In=js_eval(xC,xn,b,SZ b);x(0);aCn(b,n))RA(e1f(qjs,x))R_(et1(x)))
S X1(qp,RC(x=str0(x);Qs=xC;x(pk(&s,0)))R_(et1(x)))
S A1(qt,x(al(now())))
A2(_1,/*01*/P(!xtt,i1(x,y))Ik=xK;P(1<k,k==2&&!xtp?prj(x,A(y,PLH),2):prj(x,&y,1))
 X(Ro(run(x,&y,1))Rr(w1(xE,xx,y))Rx(((A1*)(x<<16>>16))(y))Rq(_1(xx,N(_1(xy,y))))Ru(v1[xv](y))Rw(AK(0<xv&&xv<4&&yK==2?1:ytU?yK:1,AW(xv,aV(tr,1,&y))))R_(et1(y))
  Rp(P(xn+k>9,er1(y))Im=xn-1,j=0;Ab8;i(m,b[i]=xA[i+1]==PLH&&!j?j++,y:_R(xA[i+1]))I l=MAX(0,1-j);MC(b+m,&y,8*l);_8(xx,b,m+l))
  Rs(S O C s[][4]={"","k","j","p","t","x","hex","err","argv","env","exit","js","pri","prng","sin","cos","exp","ln"};
   Li=fI(s,L(s),xv);G(&ser,kst,js1,qp,qt,frk,hex,err,qa,qe,qx,qjs,qpri,prng,ksin,kcos,kexp,klog,ed1)[i<0?L(s):i](y)))0)
A3(_2,/*001*/P(!xtt,i2(x,y,z))A a[]={y,z};Ik=xK;P(2<k,yR;prj(x,a,2))
 X(Rv(v2[xv](y,z))Ro(yR;run(x,a,2))Rr(z(w2(xE,xx,yR,z)))Rw(xv?en1(x):AK(zK,AT(tq,aA2(yR,z))))Rq(_1(xx,N(_2(xy,y,z))))Rx(P(2>k,er1(z))((A2*)(x<<16>>16))(yR,z))R_(et1(z))
  Rp(P(xn+k>9,er1(z))yR;Im=xn-1,j=0;Ab8;i(m,b[i]=xA[i+1]==PLH&&j<2?a[j++]:_R(xA[i+1]))I l=MAX(0,2-j);MC(b+m,a+j,8*l);_8(xx,b,m+l)))0)
AX(_8,/*01..1*/Q(n)P(n==1,x1(*a))P(n==2&&!xtp,Ay=*a;y(x2(y,a[1])))P(!xtt,i8(x,a,n))P(n<xK,prj(x,a,n))
 X(Ro(run(x,a,n))Rv(x=v8[xv](a,n);mrn(n-1,a+1);x)Rr(w8(xE,xx,a,n))Rq(_1(xx,N(_8(xy,a,n))))R_(et8(a,n))
  Rp(P(xn+xK>9,er8(a,n))Im=xn-1,j=0;Ab8;i(m,b[i]=xA[i+1]==PLH&&j<n?a[j++]:_R(xA[i+1]))I l=MAX(0,n-j);MC(b+m,a+j,8*l);_8(xx,b,m+l)))0)
A1(jS,cS(jc('.',str(x))))//join symbols with "."
X1(val,RA(P(!xn,x)P(xn==1,fir(x))P(xn>9,ez1(x))x=mut(x);Ay=_8(xx,&xy,xn-1);AN(1,x);x(y))RE(gZ(x))RZ_E(x)RC(x=str0(x);x(evC(xV,0)))Rc(val(enl(x)))
 RS(P(!xn,x(0);Ax=oS,y=oA;i(gn,I(gv[i],xq(as(gk[i]));yq(_R(gv[i]))))am(x,y))val(jS(x)))Rs(Li=fI(gk,gn,xv);i<0||!gv[i]?ev0():_R(gv[i]))RmM(x(_R(xy)))Ropq(AT(tA,mut(x)))
 Rr(cat10(AT(tA,mut(x)),aw+xE))Ruvw(ai(xv))R_(et1(x)))
A2(dot,/*01*/Ym(et1(y))Nn=yN;P(!n,y(xR))P(n>8,ez1(y))y=mRa(N(cA(y)));y(x8(yA,n)))
S I knd(Ax/*0*/)_(Xz(ti)XZ(tI)xt)
S A set(Ax,Li,Ay/*1i1*/)_(Q(xr==1);XA(Az=xa;xa=z(y);ytt&&!ytU?sqz(x):x)XM(Az=kv(&x);z=mut(z);Q(ztA);I(ytT&&yN-zn,x(el2(y,z)))Ij=i;i(zn,za=set(mut(za),j,ii(y,i));P(!za,za=au;x(y(z(0)))))y(aM(x,z)))
 P(knd(x)-knd(y)-tC+tc,set(cA(x),i,y))I(xtZ,N(sup(&x,&y)))C w=xw;!w?xg=yv:w==1?xh=yv:w==2?xi=yv:(xl=gl(y));x)
AA(a8,/*10..0*/Ax=*a,y=a[1];X(
 RE(Ab8;*b=gZ(x);MC(b+1,a+1,n-1<<3);a8(b,n))
 RT_E(P(y==au,mRn(n-2,a+2);Ab8;*b=a[2];b[1]=x;MC(b+2,a+3,n-3<<3);e8(AP1,b,n-1))
  Yzc(Li=gl_(y);P(!IN(i,xn),ei1(x))x=mut(x);Ab8;*b=ii(x,i);MC(b+1,a+3,n-3<<3);mRn(n-3,b+1);Az=a[2];set(x,i,Nx(z8(b,n-2))))
  I(ytZC&&n==4,Az=a[2],u=a[3];P(xtZ&&ztv&&utzZ&&(0xcf&1<<zv),ara(x,y,z,u))P(xtC&&z==av&&utcC,cC(N(ara(x,y,z,u)))))Yt(et1(x))mRn(n-1,a+1);f8(AP1,a,n))
 Rm(Az=Nx(fnd(xx,yR));ZT(z(0);mRn(n-1,a+1);f8(AP1,a,n))x=mut(x);I(ztl,z=mut(z);i(zN,I(zl==NL,zl=xN;xx=apd(xx,ztt?yR:ii(y,i));xy=apd(xy,ie(a[2],xy)))))
  Ab8;*b=xy;b[1]=z;MC(b+2,a+2,n-2<<3);xy=au;xy=Nx(z(a8(b,n)));x)
 RM(Ab8;YsS(*b=flp(x);MC(b+1,a+1,n-1<<3);flp(N(a8(b,n))))i(n,Ax=a[i];b[i]=xtM?flp(xR):xR;Q(b[i]))flp(N(x(e8(AP1,b,n)))))
 RU(mRn(n-1,a+1);x(x8(a+1,n-1)))
 R_(et1(x)))0)
S A3(a3,/*100*/a8(A(x,y,z),3))
A4(a4,/*1000*/a8(A(x,y,z,u),4))
S A a5(Ax,Ay,Az,Au,A v/*10000*/)_(a8(A(x,y,z,u,v),5))
S A3(d3,/*100*/Nm=yN;P(y==au||!m,z1(x))P(m==1,y=fir(yR);y(a3(x,y,z)))Au=prj(DOT,(A[]){PLH,drp(1,yR)},2);y=fir(yR);y(u(a4(x,y,u,z))))
A4(d4,/*1000*/Nm=yN;P(y==au||!m,x(z2(x,uR)))P(m==1,y=fir(yR);y(a4(x,y,z,u)))A v=prj(DOT,(A[]){PLH,drp(1,yR)},2);y=fir(yR);A r=y(a5(x,y,v,z,u));mr(v);r)
S AA(d8_,/*10..0*/Ax=*a,y=a[1],z=a[2];P(n==4,d4(x,y,z,a[3]))P(n==3,d3(x,y,z))en1(x))
AA(d8,/*10..0*/Ax=*a;XsS(Iv=_v(xts?x:jS(x));Li=fI(gk,gn,v);I(i<0,gk[i=gn++]=v)A*p=gv+i;I(!*p,*p=au)Ab8;*b=*p;MC(b+1,a+1,n-1<<3);*p=au;*p=_R(N(d8_(b,n))))
 I(n==3,XU(try(x,a[1],a[2])))d8_(a,n))
SN A ki(A*p,Qs)_(*p=evs(s,0);I(!*p,die(s))cns=apd(cns,*p))
A k1(A*p,Qs,Ax)_(I(!*p,ki(p,s))_1(*p,x))
A k2(A*p,Qs,Ax,Ay)_(I(!*p,ki(p,s))_2(*p,x,y))
A k8(A*p,Qs,OA*a,In)_(I(!*p,ki(p,s))n?_8(*p,a,n):*p)
AA(no8,/*10..0*/en1(*a))
