#include"a.h" // ngn/k, (c) 2019-2023 ngn, GNU AGPLv3 - https://codeberg.org/ngn/k/raw/branch/master/LICENSE
SN V cGH(O V*RES a,V*RES b,U n)_(O G*p=a;H*r=b;i(n+15&-16,r[i]=p[i]))
SN V cGI(O V*RES a,V*RES b,U n)_(O G*p=a;I*r=b;i(n+ 7& -8,r[i]=p[i]))
SN V cHG(O V*RES a,V*RES b,U n)_(O H*p=a;G*r=b;i(n+31&-32,r[i]=p[i]))
SN V cHI(O V*RES a,V*RES b,U n)_(O H*p=a;I*r=b;i(n+ 7& -8,r[i]=p[i]))
SN V cHL(O V*RES a,V*RES b,U n)_(O H*p=a;L*r=b;i(n+ 3& -4,r[i]=p[i]))
SN V cIG(O V*RES a,V*RES b,U n)_(O I*p=a;G*r=b;i(n+ 7& -8,r[i]=p[i]))
SN V cIH(O V*RES a,V*RES b,U n)_(O I*p=a;H*r=b;i(n+ 7& -8,r[i]=p[i]))
SN V cIL(O V*RES a,V*RES b,U n)_(O I*p=a;L*r=b;i(n+ 3& -4,r[i]=p[i]))
SN V cLG(O V*RES a,V*RES b,U n)_(O L*p=a;G*r=b;i(n+ 3& -4,r[i]=p[i]))
SN V cLH(O V*RES a,V*RES b,U n)_(O L*p=a;H*r=b;i(n+ 3& -4,r[i]=p[i]))
SN V cLI(O V*RES a,V*RES b,U n)_(O L*p=a;I*r=b;i(n+ 3& -4,r[i]=p[i]))
SN V cLF(O V*RES a,V*RES b,U n)_(O L*p=a;F*r=b;i(n+ 3& -4,r[i]=p[i]==NL  ?NF:p[i]))
SN V cFL(O V*RES a,V*RES b,U n)_(O F*p=a;L*r=b;i(n+ 3& -4,r[i]=p[i]!=p[i]?NL:p[i]))
X1(flp,Rt(enl(enl(x)))R_(enl(x))RM(A y=kv(&x);am(x,y))
 Rm(A y=kv(&x);Y(RA(I(yn>1,L n=cfm(yA,yn);P(n<0,x(el1(y)))i(yn,A z=ya;I(ztt,y=mut(y);ya=rsz(n,z))))aM(x,y))RT_A(aM(x,e1f(enl,y)))R_(en2(x,y)))0)
 RA(U m=xn;L n=cfm(xA,m|!m);P(n==-1,enl(x))P(n<0,el1(x))C t=_t(xx);I(t<tM&&t-tE,i(m,A y=xa;B(yt-t,t=0)))E(t=0)A y=aA(n);
  P(!t,i(n|!n,A z=aA(m);j(m,zA[j]=ii(xA[j],i))I(!zn,zx=mkn(zx))ya=sqz(z))x(0);I(!yn,yx=mkn(yx))y)
  U w=Tw[t]-3;j(n|!n,A z=yA[j]=an(m,t);S4(w,i(m,zg=_G(xa)[j]),i(m,zh=_H(xa)[j]),i(m,zi=_I(xa)[j]),i(m|!m,zl=_L(xa)[j])I(w==4,I(!m,zx=mkn(_R(zx)))yA[j]=sqz(mRa(z)))))
  x(0);I(!n,yx=mkn(yx))y))
V tilV(V*p,L v,L n,U w){L*a=p,k=G(0x101010101010101ll,0x1000100010001ll,1ll<<32|1,1)[w],d=k<<3-w;v*=k;v+=G(0x706050403020100ll,0x3000200010000ll,1ll<<32,0)[w];
 i((n-1>>3-w)+4&-4,a[i]=v;v+=d)}
A1(gZ,Lij x(0);P(i<0,x=az(i);x(add(x,gZ(aE(0,j-i)))))C t=MAX(tZ(i),tZ(j-1));x=an(j-i,t);tilV(xV,i,j-i,t-tG);x)
X1(til,RA(K1("{x@'!#'x}",x))Rz(L n=gl(x);n*=n!=-n;aE(MIN(0,n),MAX(0,n)))RZ(K1("{(*a)#'&'x#'1_a:|*\\|x,1}",x))RS(I k=_v(jS(x));A y=oS;i(gn,I(gk[i]>>32==k,yq(as(gk[i]))))y)
 RmM(x(_R(xx)))Ro(val(x))Rs(til(enl(x)))R_(et1(x)))
X1(whr,Rz(whr(enl(x)))RA(K1("{$[`A~@x;(,&#'*'x),,'/x@\\:!0|/#'x:o'x;,&x]}",x))Rm(A y=kv(&x);x(x1(Nx(whr(y)))))RE(whr(gZ(x)))R_(et1(x))
 RZ_E(L m=xn,n=addfZ(0,x);P(n<0||minfZ(0,x)<0,ed1(x))C t=tZ(m-!!m);P(t>tI,ez1(x))A y=an(n,t);I w=xw;
  Mx(S4(t-tG,{G*r=yV;S4(w,i(m,j(xg,*r++=i)),i(m,j(xh,*r++=i)),i(m,j(xi,*r++=i)),i(m,j(xl,*r++=i)))},
             {H*r=yV;S4(w,i(m,j(xg,*r++=i)),i(m,j(xh,*r++=i)),i(m,j(xi,*r++=i)),i(m,j(xl,*r++=i)))},
             {I*r=yV;S4(w,i(m,j(xg,*r++=i)),i(m,j(xh,*r++=i)),i(m,j(xi,*r++=i)),i(m,j(xl,*r++=i)))},))y))
X1(rev,Rm(A y=kv(&x);am(rev(x),rev(y)))RM(A y=kv(&x);aM(x,e1f(rev,y)))Rt(x)RE(rev(gZ(x)))
 R_(P(xn<2,x)x=mut(x);U n=xn;I w=xw;S4(w,i(n>>1,SWP(xg,xG[n-1-i])),i(n>>1,SWP(xh,xH[n-1-i])),i(n>>1,SWP(xi,xI[n-1-i])),i(n>>1,SWP(xl,xL[n-1-i])))x))
A1(typ,x(as(TS[xt])))
A1(len,x(az(xN)))
U _N(A x/*0*/){X(RE(Lij j-i)RT_E(xn)Rm(_N(xy))RM(_N(_x(xy)))R_(1))}
Y2(fil,RmMA(e2f(fil,x,y))Rt(YU(y-au?y:xR)fir(fil(x,enl(y))))R_(K2("{@[y;&^y;:;x]}",x,y)))
X2(crt,Rt(fil(x,y))R_(en1(y))
 RT(I v=rnk(y);P(!v,crt(x,enl(y)))
  P(v>0&&rnk(x)==v,I(xtE&&ytE,Lij L k=*yL,l=yL[1];P(k<=i,y(0);aE(MAX(i,l),MAX(j,l)))P(j<=l,y(0);aE(i,MIN(j,k))))K2("{x@&^y?x}",x,y))
  K2("{x@&~(!0),x~\\:y}/",x,y)))
A wdn(A x,U i,U j,U n)_(C t=xt;Q(xtZC);A y=an(n,t+1);Mx(G(&cGH,cHI,cIL,cLF,0,cGH)[t-tG](xV+TW[t]*i,yV,j-i))y)
X1(cA,RA(x)Rt(aA1(x))Rm(et1(x))R_(U n=xN;A y=aA(n);i(n|!n,ya=ii(x,i))x(0);I(!n,yx=mkn(yx))y))
X1(cC,RmMA(e1f(cC,x))RcC(x)RG(AT(tC,mut(x)))Rz(ac(gl(x)))RE(cC(gZ(x)))R_(cC(N(cG(x)))))
X1(cG,RmMA(e1f(cG,x))RG(x)Rt(cI(x))RC(AT(tG,mut(x)))R_(x=N(cI(x));A y=aG(xn);Mx(cIG(xV,yV,yn))y))
X1(cH,RmMA(e1f(cH,x))RH(x)Rt(cI(x))R_(x=N(cI(x));A y=an(xn,tH);Mx(cIH(xV,yV,yn))y))
X1(cI,RmMA(e1f(cI,x))RI(x)Rzc(ai(gl(x)))RfF(cI(N(cL(x))))R4(tG,tH,tL,tC,A y=aI(xn);I i=xt-tG;Mx(G(&cGI,cHI,0,cLI,0,cGI)[i](xV,yV,yn))y)RE(gZ(x))R_(et1(x)))
X1(cL,RmMA(e1f(cL,x))RlL(x)Ric(al(xv))RF(A y=aL(xn);Mx(cFL(xV,yV,yn))y)Rf(al(gf(x)))RE(cL(gZ(x)))R_(x=N(cI(x));A y=aL(xn);Mx(cIL(xV,yV,yn))y))
X1(cF,RmMA(e1f(cF,x))RfF(x)Rzc(af(gl(x)))R_(x=N(cL(x));A y=aF(xn);Mx(cLF(xV,yV,yn))y))
X1(cS,RmMA(e1f(cS,x))RsS(x)RC(x=str0(x);x(sym(xV)))Rc(as(xv))R_(et1(x)))
X1(pI,RmMA(e1f(pI,x))Rc(pI(enl(x)))RC(x=str0(x);Q s=xV;P(!*s,x(_R(cn[tl])))L v=pl(&s);x(*s?_R(cn[tl]):az(v)      ))R_(et1(x)))
X1(pF,RmMA(e1f(pF,x))Rc(pF(enl(x)))RC(x=str0(x);Q s=xV;P(!*s,x(_R(cn[tf])))L v=pf(&s);x(*s?_R(cn[tf]):aV(tf,1,&v)))R_(et1(x)))
A1*cT[]={[tA]=cA,cL,cG,cH,cI,cL,cF,cC,cS};
X1(csti,RmMA(e1f(csti,x))RF(sqzZ(cL(x)))Rf(az(gf(x)))RC(cG(x))Rc(ai(xv))Ruvw(ai(xv))RzZ(x)R_(et1(x)))
Y2(cstz,RmMA(e2f(cstz,x,y))RC(K2("{y@(!x)+(x<0)*#y}",x,y))Rc(cst(x,enl(y)))R_(et1(y)))
X2(cst,Rs(I v=xv;P(v-(C)v,ed1(y))G(&csti,cF,cC,cS,pI,pF,ed1)[si("ifcsIF",v+'s'*!v)](y))Rz(cstz(x,y))R_(et1(y)))
X1(sqzZ,RH(i(xn,P(xh-(G)xh,x))cG(x))RI(i(xn,P(xi-(H)xi,x))sqzZ(cH(x)))RL(i(xn,P(xl-(I)xl,x))sqzZ(cI(x)))R_(x))
A1(sqz,P(!xtA,x)N n=xn;A y=xx;C t=yt;P(ytMT||ytU,x)
 I(ytz,P(!n,x(oG))I l=0;i(n,A y=xa;I(ytl,l=1)E(P(!yti,x)))I(l,t=tL)E(I a=0;i(n,A y=xa;a=MIN(a,MIN(yv,~yv)))t=tZ(a)))E(i(n,P(t-_t(xa),x)))
 Ym(i(n,P(!mtc_(yx,_x(xa)),x))y=aM(_R(yx),e1f(rs0,_R(yy)));i(n,yq(_R(xa)))x(y))
 y=an(n,TT[t]);I v=yw;I(v<3,G(&cLG,cLH,cLI)[v](xV,yV,n))E(i(n,yl=gl_(xa)))x(y))
B tru(A x/*1*/)_(B v=xtU?x!=au:xtt?!!gl_(x):!!xN;x(0);v)
X1(imx,RZC_E(imn(inv(x)))RF(imx(of1(x)))RE(Lij x(0);az(j-i?j-i-1:NL))R_(fir(N(dsc(x)))))
X1(imn,RF(imn(of1(x)))RE(Lij x(0);az(NL*(i==j)))R_(fir(N(asc(x))))
 RZC_E(N n=xn;L j=n?0:NL;S4(xw,{G v=*xG;i(n,I(xg<v,v=xg;j=i))},{H v=*xH;i(n,I(xh<v,v=xh;j=i))},{I v=*xI;i(n,I(xi<v,v=xi;j=i))},{L v=*xL;i(n,I(xl<v,v=xl;j=i))})x(az(j))))
