#include"a.h" // ngn/k, (c) 2019-2023 ngn, GNU AGPLv3 - https://codeberg.org/ngn/k/raw/branch/master/LICENSE
#define c_(T,R,p) SN V c##T##R(OV*RES v,V*RES w,Nn)_(O T*RES a=v;R*RES r=w;i(PD(n,p),r[i]=a[i]))
c_(B,H,r)c_(H,B,a)c_(B,I,r)c_(I,B,a)c_(L,B,a)c_(H,I,r)c_(I,H,a)c_(H,L,r)c_(L,H,a)c_(I,L,r)c_(L,I,a)
SN V cLF(OV*RES v,V*RES w,Nn)_(O L*RES a=v;F*RES r=w;i(n+3&~3,r[i]=a[i]==NL?NF:a[i]))
SN V cFL(OV*RES v,V*RES w,Nn)_(O F*RES a=v;L*RES r=w;i(n+3&~3,r[i]=a[i]==NF?NL:a[i]))
X1(flp,Rm(Ay=kv(&x);YA(I(yn>1,Ln=cfm(yA,yn);P(n<0,x(el1(y)))i(yn,Az=ya;I(ztt,y=mut(y);ya=rsz(n,z))))aM(x,y))YT(aM(x,e1f(enl,y)))en2(x,y))RM(Ay=kv(&x);am(x,y))Rt(enl(enl(x)))R_(enl(x))
 RA(Nm=xn;Ln=cfm(xA,m|!m);P(n==-1,enl(x))P(n<0,el1(x))Ct=_t(xx);I(t<tM,i(m,Ay=xa;B(yt-t,t=0)))E(t=0)Ay=aA(n);
  P(!t,i(n|!n,Az=aA(m);j(m,zA[j]=ii(xA[j],i))I(!zn,zx=mkn(zx))ya=sqz(z))x(0);I(!yn,yx=mkn(yx))y)
  I w=Tw[t];j(n|!n,Az=yA[j]=an(m,t);S4(w,i(m,zb=_B(xa)[j]),i(m,zh=_H(xa)[j]),i(m,zi=_I(xa)[j]),i(m|!m,zl=_L(xa)[j])I(w==4,I(!m,zx=mkn(_R(zx)))yA[j]=sqz(mRa(z)))))
  x(0);I(!n,yx=mkn(yx))y))
V tilV(V*p,Ln,I w){L*a=p,v=A(0x706050403020100ll,0x3000200010000ll,1ll<<32,0)[w],d=A(0x808080808080808ll,0x4000400040004ll,2ll<<32|2,1)[w];LI(a)i(PD((n-1>>3-w)+1,a),a[i]=v;v+=d)}
AL(tilL,P(n<0,n==(I)n?add(ai(n),N(tilL(-n))):ed0())P(n>1<<30,ez0())Ax=an(n,tZ(n-1));tilV(xV,n,xt-tB);x)
X1(til,
// Rz(tilL(gl(x)))
 Rz(Ln=gl(x);aE(MIN(0,n),MAX(0,n)))
 RZ(K1("{(*a)#'&'x#'1_a:|*\\|x,1}",x))RmM(x(_R(xx)))Ro(val(x))RS(K1("{x:\".\"/$x,`;`$(#x)_'(x~/:@[;!#x]')#$!.0#`}",x))R_(et1(x)))
X1(whr,Rz(whr(enl(x)))RA(K1("{$[`A~@x;(,&#'*'x),,'/x@\\:!0|/#'x:o'x;,&x]}",x))Rm(Ay=kv(&x);x(x1(Nx(whr(y)))))RM(et1(x))R_(et1(x))RE(whr(gZ(x)))
 RZ_E(Lm=xn,n=addfZ(0,x);P(n<0||minfZ(0,x)<0,ed1(x))Ct=tZ(m-!!m);P(t>tI,ez1(x))Ay=an(n,t);I w=xw;
  Mx(S4(t-tB,{B*r=yV;S4(w,i(m,j(xb,*r++=i)),i(m,j(xh,*r++=i)),i(m,j(xi,*r++=i)),i(m,j(xl,*r++=i)))},
             {H*r=yV;S4(w,i(m,j(xb,*r++=i)),i(m,j(xh,*r++=i)),i(m,j(xi,*r++=i)),i(m,j(xl,*r++=i)))},
             {I*r=yV;S4(w,i(m,j(xb,*r++=i)),i(m,j(xh,*r++=i)),i(m,j(xi,*r++=i)),i(m,j(xl,*r++=i)))},))y))
X1(rev,Rm(Ay=kv(&x);am(rev(x),rev(y)))RM(Ay=kv(&x);aM(x,e1f(rev,y)))Rt(x)RE(rev(gZ(x)))
 R_(P(xn<2,x)x=mut(x);Ii=0,j=xn-1,w=xw;W(i<j,S4(w,SWP(xb,xB[j]),SWP(xh,xH[j]),SWP(xi,xI[j]),SWP(xl,xL[j]))i++;j--)x))
A1(typ,x(as(TS[xt])))A1(len,x(az(xN)))N _N(Ax/*0*/){X(RE(Lij j-i)RT_E(xn)Rm(_N(xy))RM(_N(_x(xy)))R_(1))}
S A1(cSI,Q(xtS||xtI)Ct=tS^tI^xt;xr-1?x(aV(t,xn,xV)):AT(t,x))
X1(unq,RM(en1(x))Rm(unq(val(x)))RE(x)RS(cSI(unq(cSI(x))))Rz(rndF(gl(x)))R_(et1(x))RBC(C a[256]={};Ay=an(0,xt);i(xn,UC c=xc;I(!a[c],a[c]=1;y=apc(y,xc)))x(y))
 R5(tA,tH,tI,tL,tF,P(xn<2,x)P(xn<<xw<pg&&!xtA,K1("{x@&(x?x)=!#x}",x))K1("{x@i@<i@:&@[;0;:;1]@~~':x@i:<x}",x)))
Y2(fil,/*01*/RmMA(e2f(fil,x,y))Rt(YU(y==au?xR:y)fir(fil(x,enl(y))))R_(K2("{@[y;&^y;:;x]}",x,y)))
A2(exc,/*01*/Xt(fil(x,y))P(xtmM||ytmM,en1(y))Yt(exc(x,enl(y)))P(!xn||!yn,y(xR))Ik=rnk(x);k>0&&k==rnk(y)?K2("{x@&^y?x}",x,y):K2("{x@&~(!0),x~\\:y}/",x,y))
A wdn(Ax,Ni,Nj,Nn)_(Ct=xt;Q(xtZC);Ay=an(n,t+1);Mx(A(&cBH,cHI,cIL,cLF,0,cBH)[t-tB](xV+TW[t]*i,yV,j-i))y)
X1(cA,RA(x)Rt(aA1(x))Rm(et1(x))R_(Nn=xN;Ay=aA(n);i(n|!n,ya=ii(x,i))x(0);I(!n,yx=mkn(yx))y))
X1(cC,RcC(x)RB(AT(tC,mut(x)))Rz(ac(gl(x)))RE(cC(gZ(x)))R_(cC(N(cB(x)))))
X1(cB,RB(x)Rt(cI(x))RC(AT(tB,mut(x)))R_(x=N(cI(x));Ay=aB(xn);Mx(cIB(xV,yV,yn))y))
X1(cH,RH(x)Rt(cI(x))R_(x=N(cI(x));Ay=an(xn,tH);Mx(cIH(xV,yV,yn))y))
X1(cI,RI(x)Rzc(ai(gl(x)))RfF(cI(N(cL(x))))R4(tB,tH,tL,tC,Ay=aI(xn);Ii=xt-tB;Mx(A(&cBI,cHI,0,cLI,0,cBI)[i](xV,yV,yn))y)RE(gZ(x))R_(et1(x)))
X1(cL,RlL(x)Ric(al(xv))RF(Ay=aL(xn);Mx(cFL(xV,yV,yn))y)Rf(al(gf(x)))RE(cL(gZ(x)))R_(x=N(cI(x));Ay=aL(xn);Mx(cIL(xV,yV,yn))y))
X1(cF,RfF(x)Rzc(af(gl(x)))R_(x=N(cL(x));Ay=aF(xn);Mx(cLF(xV,yV,yn))y))
X1(cS,RsS(x)RC(x=str0(x);x(sym(xV)))Rc(as(xv))RmMA(e1f(cS,x))R_(et1(x)))
X1(pI,Rc(pI(enl(x)))RC(x=str0(x);Qs=xV;P(!*s,x(_R(cn[tl])))Lv=pl(&s);x(*s?_R(cn[tl]):az(v)))RmMA(e1f(pI,x))R_(et1(x)))
X1(pF,Rc(pF(enl(x)))RC(x=str0(x);Qs=xV;P(!*s,x(_R(cn[tf])))Fv=pf(&s);x(*s?_R(cn[tf]):af(v)))RmMA(e1f(pF,x))R_(et1(x)))
A1*cT[]={[tA]=cA,cL,cB,cH,cI,cL,cF,cC,cS};
X1(csti,RF(sqzZ(cL(x)))Rf(az(gf(x)))RC(cB(x))Rc(ai(xv))Ruvw(ai(xv))RzZ(x)R_(et1(x)))
A2(cst,/*01*/YmMA(e2f(cst,x,y))
 X(Rz(Y(RC(K2("{y@(!x)+(x<0)*#y}",x,y))Rc(cst(x,enl(y)))R_(et1(y)))0)
   Rs(Iv=xv;P(v-(C)v,ed1(y))A(&csti,cF,cC,cS,pI,pF,ed1)[si("ifcsIF",v+'s'*!v)](y))
   RS(e2f(cst,x,y))
   R_(et1(y)))0)
X1(sqzZ,RH(i(xn,P(xh-(B)xh,x))cB(x))RI(i(xn,P(xi-(H)xi,x))sqzZ(cH(x)))RL(i(xn,P(xl-(I)xl,x))sqzZ(cI(x)))R_(x))
A1(sqz,P(!xtA,x)Nn=xn;Ay=xx;Ct=yt;P(ytMT||ytU,x)
 I(ytz,P(!n,x(oB))I l=0;i(n,Ay=xa;I(ytl,l=1)E(P(!yti,x)))I(l,t=tL)E(I a=0;i(n,Ay=xa;a=MIN(a,MIN(yv,~yv)))t=tZ(a)))E(i(n,P(t-_t(xa),x)))
 Ym(i(n,P(!mtc_(yx,_x(xa)),x))y=aM(_R(yx),e1f(rs0,_R(yy)));i(n,yq(_R(xa)))x(y))
 y=an(n,TT[t]);Iv=yw;I(v<3,A(&cLB,cLH,cLI)[v](xV,yV,n))E(i(n,yl=gl_(xa)))x(y))
L tru(Ax/*1*/)_(Lv=xtU?x!=au:xtt?gl_(x):xN;x(0);v)
X1(imx,RZC_E(imn(inv(x)))RF(imx(of1(x)))RE(Lij x(0);az(j-i?j-i-1:NL))R_(fir(N(dsc(x)))))
X1(imn,RF(imn(of1(x)))RE(Lij x(0);az(NL*(i==j)))R_(fir(N(asc(x))))
 RZC_E(Nn=xn;Lj=n?0:NL;S4(xw,{Bv=*xB;i(n,I(xb<v,v=xb;j=i))},{Hv=*xH;i(n,I(xh<v,v=xh;j=i))},{Iv=*xI;i(n,I(xi<v,v=xi;j=i))},{Lv=*xL;i(n,I(xl<v,v=xl;j=i))})x(az(j))))
