#include"a.h" // ngn/k, (c) 2019-2022 ngn, GNU AGPLv3 - https://codeberg.org/ngn/k/raw/branch/master/LICENSE
SN A2(enc,/*01*/P(!xtzZ,en1(y))P(x==ai(2)&&ytz&&gl_(y)<0,x=rsh(64,xR);x(enc(x,y)))
 Ii=ytt;x=K("{$[0>&/x;`err\"domain\"; `i~@x;|x!-1_![-x;]\\y; x!'|(,y),y{(-y)!x}\\|1_x]}",xR,y);!x||xN?x:x(i?oB:oA))
SN A2(dec,/*01*/K("{z+x*y}/[0;;]",xR,y))
SN A scC(Cc    ,C*p,Ln)_(           Ax=oA;C*q;W((q=MC(p,c,n  )),xq(aCm(p,q));n-=q-p+1;p=q+1)I(n||c-10&&xn,xq(aCn(p,n)))x)SN A sc(Cc    ,Ax)_(XC(x(scC(c,  xV,xn)))et1(x))A1(spl,sc(10,x))
SN A sCC(C*s,Lm,C*p,Ln)_(P(!m,el0())Ax=oA;C*q;W((q=MM(p,n,s,m)),xq(aCm(p,q));n-=q+m-p;p=q+m)I(n||      xn,xq(aCn(p,n)))x)SN A sC(C*s,Lm,Ax)_(XC(x(sCC(s,m,xV,xn)))et1(x))
SN L jN(Lm,Ax/*0*/)_(P(!xtA,-1)Ln=(xn-!!xn)*m;i(xn,Ay=xa;P(!ytcC,-1)n+=yN)n)//total length or -1
A jc(Cc,   Ax)_(XC(jc(c,  flp(flp(x))))Ln=jN(1,x);P(n<0,et1(x))Ay=aC(n);C*p=yV;i(xn,I(i,*p++=c        )Az=xa;I(ztc,*p++=zv)E(Mc(p,zV,zn);p+=zn))x(y))
A jC(Qs,Nm,Ax)_(XC(jC(s,m,flp(flp(x))))Ln=jN(m,x);P(n<0,et1(x))Ay=aC(n);C*p=yV;i(xn,I(i,Mc(p,s,m);p+=m)Az=xa;I(ztc,*p++=zv)E(Mc(p,zV,zn);p+=zn))x(y))
L cfm(OA*a/*0*/,In)_(Lm=-1;i(n,Ax=a[i];I(!xtt,Lv=xN;P(m>=0&&m-v,-2)m=v))m)
S A o1f(A1 f,Ax/*f0*/)_(f==len?oB:f==til||f==str?oA:xR)S A2(o1,/*00*/xtu?o1f(v1[xv],y):oA)
S A o2f(A2 f,Ax,Ay/*f00*/)_(f==bng?oB:oA)              S A3(o2,/*000*/xtv?o2f(v2[xv],y,z):oA)
SN AX(em,Az=oS;Ik=0;i(n,Ay=a[i];I(ytm,k++;z=cat11(z,_R(yx))))I(k>1,z=unq(z))Ab8;i(n,Ay=b[i]=a[i];I(ytm,Au=kv(&y);uq(ide(x,u));b[i]=u(u1(y(fil(ai(yn),fnd(y,zR)))))))AX e8;x=e8(x,b,n);P(!x,z(x))z(dct(z,x)))
A e1f(A1 f,Ax)_(Xt(f(x))Xm(Ay=kv(&x);am(x,Nx(e1f(f,y))))I b=xtA&&xr==1;Nn=xN;P(!n,x(o1f(f,x)))Ay=oA;i(n,Az=f(b?xa:ii(x,i));B(!z,I(b,mrn(xn-i-1,xA+i+1))y=y(0))yq(z))I(b,x=AN(0,x))x(y))
SN A2(e1,/*01*/ Xu(e1f(v1[xv],y))Yt(x1(y))Ym(em(x,&y,1))Nm=yN;P(!m,y(o1(x,y)))P(ytA&&yr==1,y=AN(0,y);Au=oB;i(m,Az=x1(ya);B(!z,u=u(0);mrn(m-i-1,yA+i+1))uq(z))y(u))
                                                                                                     Au=oB;i(m,Az=x1(ii(y,i));B(!z,u=u(0))uq(z))y(u))
A l2f(A2 f,Ax,Ay/*f01*/)_(Xt(f(x,y))Xm(Az=N(l2f(f,xy,y));am(_R(xx),z))Nn=xN;P(!n,y(o2f(f,x,y)))Au=oA;i(xN,A w=ii(x,i),v=f(w,yR);mr(w);B(!v,u=u(0))uq(v))y(u))
SN A r2f(A2 f,Ax,Ay/*f01*/)_(Yt(f(x,y))Ym(Az=Ny(r2f(f,x,_R(yx)));y(am(_R(yx),z)))Nn=yN;P(!n,y(o2f(f,x,y)))Au=oA;i(yN,A v=f(x,ii(y,i));B(!v,u=u(0))uq(v))y(u))
SN A3(l2,/*001*/Xv(l2f(v2[xv],y,z))Yt(y(x2(y,z)))Ym(x=prj(x,A(PLH,z),2);x(e1(x,yR)))Nn=yN;P(!n,z(o2(x,y,z)))Au=oA;i(yN,A w=ii(y,i),v=x2(w,zR);mr(w);B(!v,u=u(0))uq(v))z(u))
NI A3(r2,/*001*/ Xv(r2f(v2[xv],y,z))Zt(y(x2(y,z)))Zm(x=prj(x,A(yR,PLH),2);x(e1(x,z)))Nn=zN;P(!n,z(o2(x,y,z)))Au=oA;i(zN,A v=x2(y,ii(z,i));B(!v,u=u(0))uq(v))z(u))
SN AX(l8,Ab8;Mc(b,a,8*n);*b=PLH;x=prj(x,b,n);x(e1(x,*a)))
SN A3(e2,/*001*/P(xtv,e2f(v2[xv],y,z))Yt(r2(x,y,z))Zt(l2(x,y,z))P(ytm||ztm,y(em(x,A(yR,z),2)))Nm=yN;P(m-zN,el1(z))P(!m,z(xtv&&xv<11?yR:oA))
 Au=0;Ct=ztA&&zr==1;i(m,A w=ii(y,i),v=x2(w,t?za:ii(z,i));mr(w);B(!v,I(u,u=u(0))I(t,mrn(m-i-1,zA+i+1)))I(!u,u=v?AN(0,an(c3(ti,_t(v),ts)?TT[_t(v)]:tA,m)):0)uq(v))mr(t?AN(0,z):z);u)
AX(e8,P(n==1,e1(x,*a))P(n==2,Ay=*a;y(e2(x,y,a[1])))Ab8;Ct[8];Lm=-1;i(n,Ay=b[i]=a[i];Ym(em(x,a,n))t[i]=ytP?0:ytt?1:ytA?2+(yr>1):4;I(t[i]>1,L l=yN;P(m>=0&&m-l,el8(a,n))m=l))
 P(m<0,x8(a,n))i(n,I(t[i]==1,_r(a[i])+=m))Au=0;I(!m,u=x==LEN?oB:n==2&&xtv&&xv<11?_R(a[!_N(a[1])]):oA)//t[i] 0:pkdatm,1:refatm,2:tA(r=1),3:tA,4:other
 j(m,i(n,Ay=a[i];I(t[i]==2,b[i]=yA[j])I(t[i]>2,b[i]=ii(y,j)))Az=x8(b,n);B(!z,I(u,u=u(0))i(n,Ay=a[i];I(t[i]==1,yr-=m-j-1)I(t[i]==2,mrn(m-j-1,yA+j+1))))I(!j,u=c3(ti,zt,ts)?AN(0,an(TT[zt],m)):oA)uq(z))
 i(n,mr(t[i]-2?a[i]:AN(0,a[i])))u)
S I arf2(A2 f)_((SZ(V*)-8?fI:fL)(v2+1,10,(L)f)!=NL)
A e2f(A2 f,Ax,Ay/*f01*/)_(Ik=2*xtt+ytt;P(k==3,f(x,y))
 P(xtm||ytm,P(xtm>ytm,Az=N(e2f(f,xy,y));am(_R(xx),z))P(xtm<ytm,Az=Ny(e2f(f,x,_R(yy)));y(am(_R(yx),z)))
  Az=unq(cat(xx,_R(yx)));x=x1(zR);y=y(y1(zR));I(arf2(f),Au=ai(f==mul||f==dvd);x=fil(u,x);y=fil(u,y))am(z,Nz(x(e2f(f,x,y)))))
 P(!k&&xN-yN,el1(y))
 Nn=k<2?xN:yN;Az=o2f(f,x,y);i(n,A v=ii(x,i);Au=f(v,ii(y,i));mr(v);B(!u,z=z(0))zq(u))y(z))
SN A2(cs,/*01*/Az=yR,v=yR,u=enl(y);W(1,z=yR;y=x1(y);P(!y,mr(v);z(u(0)))Im=mtc_(y,z)||mtc_(y,v);z(0);B(m)uq(yR))mr(v);y(u))
SN A2(cf,/*01*/Az=yR,u;W(1,zR;u=x1(z);B(!u)P(mtc_(u,y)||mtc_(u,z),y(u(z)))z=z(u))y(z(u)))
SN A ns(Ax,Lm,Ay/*0m1*/)_(Az=oA;i(m,zq(yR);y=x1(y);B(!y))y?zq(y):z(y))
SN A nf(Ax,Lm,Ay/*0m1*/)_(Az=0;i(m,y=x1(y);B(!y))y)
SN A3(ws,/*001*/Au=enl(zR);W(1,A w=y1(zR);B(!w,u=u(0))B(!tru(w))z=x1(z);P(!z,u(0))uq(zR))z(u))
SN A3(wf,/*001*/Au=0;W(1,A w=y1(zR);B(!w,z=z(0))B(!tru(w))z=x1(z);P(!z,0))z)
SN A nS(Ax,Lm,OA*a,Nn/*0m1n*/)_(P(n==1,ns(x,m,*a))m=max(0,m);Az=aA(n+m),*b=zV;zn=n;Mc(b,a,8*n);i(m,mRn(n,b);b[n]=Nz(x8(b,n));zn++;b++)sqz(z))
SN A wS(Ax,Ay,OA*a,Nn/*001n*/)_(P(n==1,ws(x,y,*a))Ab8;Mc(b,a,8*n);mRn(n,b);Az=sqz(aV(tA,n,b));
 W(1,Au=y1(ii(z,zn-1));B(!u,z=z(0))B(!tru(u))mRn(n-1,b+1);u=x8(b,n);B(!u,*b=au;z=z(0))Mm(b,b+1,8*n-8);b[n-1]=u;zq(uR))mrn(n,b);z)
SN A nF(Ax,Lm,OA*a,Nn/*0m1n*/)_(P(n==1,nf(x,m,*a))las(N(nS(x,m,a,n))))
SN A wF(Ax,Ay,OA*a,Nn/*001n*/)_(P(n==1,wf(x,y,*a))las(N(wS(x,y,a,n))))
SN A3(nws2,/*001*/Yz(ns(x,gl_(y),z))YF(ws(x,y,z))et1(z))
SN A3(nwf2,/*001*/Yz(nf(x,gl_(y),z))YF(wf(x,y,z))et1(z))
SN AX(nws,Ay=*a;P(n==2,y(nws2(x,y,a[1])))Yz(nS(x,gl(y),a+1,n-1))YF(y(wS(x,y,a+1,n-1)))et8(a,n))
SN AX(nwf,Ay=*a;P(n==2,y(nwf2(x,y,a[1])))Yz(nF(x,gl(y),a+1,n-1))YF(y(wF(x,y,a+1,n-1)))et8(a,n))
SN A2(raz,/*01*/xR;i(yN,x=cat11(x,ii(y,i)))y(x))
A2(f1,/*01*/Yt(y)P(xtv&&xv<11&&ytZDC,arf(x,0,y))P(!yN,y(ide(x,y)))P(x==CAT,Au=rsh(0,ii(y,0));u(raz(u,y)))Az=ii(y,0);i(yN-1,z=z(x2(z,ii(y,i+1)));B(!z))y(z))
SN A3(f2,/*001*/Zt(x2(y,z))P(xtv&&xv<11&&ytzdc&&ztZDC,arf(x,y,z))P(x==CAT,raz(y,z))yR;i(zN,y=y(x2(y,ii(z,i)));B(!y))z(y))
AX(f8,P(n==1,f1(x,*a))P(n==2,Ay=*a;y(f2(x,y,a[1])))n--;Ay=*a++,z=*a;Lm=cfm(a,n);P(m==-1,y?x8(a-1,n+1):z)P(m<0,I(y,y(0))el8(a,n))P(!m&&!y,x=ide(x,z);mrn(n,a);x)
 Li=!y;I(i,y=ii(z,0))Ab8;W(i<m,*b=y;j(n,b[j+1]=ii(a[j],i))y=x8(b,n+1);B(!y)i++)mrn(n-1,a+1);z(y))
SN A3(s2,/*001*/Zt(x2(y,z))Zm(Au=kv(&z);am(z,Nz(s2(x,y,u))))yR;P(!zN,y(z))P(xtv&&xv<11&&ytzc&&ztZC,y(ars(x,y,z)))Au=oA;i(zN,y=y(x2(y,ii(z,i)));P(!y,z(u(0)))uq(yR))y(z(u)))
SN A2(s1,/*01*/Yt(y)P(!yN,y)Ym(Az=kv(&y);am(y,Ny(s1(x,z))))P(x==CAT,s2(x,ce[tA],y))P(xtv&&xv<11&&ytZC,ars(x,0,y))Ni=0,n=yN;Az=ii(y,0),u=enl(zR);W(++i<n,z=N(z(x2(z,ii(y,i))));uq(zR))z(y(u)))
SN AX(s8,P(n==1,s1(x,*a))P(n==2,Ay=*a;y(s2(x,y,a[1])))Ay=*a++;n--;Lm=cfm(a,n);P(m==-2,y(el8(a,n)))Az=oA;Ab8;i(m,*b=y;j(n,b[j+1]=ii(a[j],i))y=x8(b,n+1);P(!y,mrn(n,a);z(0))zq(yR))mrn(n,a);y(z))
SN A3(p2,/*001*/Zm(Au=kv(&z);am(z,Nz(p2(x,y,u))))Zt(et1(z))P(!zN,z)P(xtv&&xv<11&&ytzc&&ztZC,arp(x,y,z))yR;Au=oA;i(zN,A v=ii(z,i);y=x2(v,y);mr(v);P(!y,z(u(0)))uq(y);y=ii(z,i))y(z(u)))
SN A2(p1,/*01*/Az=ide(x,y);z(p2(x,z,y)))
SN ALA(win,P(n<0,ed1(x))K("{[n;x]x(!n)+/:!0|1-n-#x}",az(n),x))
SN A3(ste,/*001*/Yz(e1(x,N(win(gl_(y),z))))et1(z))
SN A2 binD;
SN A2(binZ,/*01*/Q(xtZC)
 YZC(P(xn-(I)xn,ez1(y))I wx=xw,wy=yw;P(!wx,wy?K("{@[x'`c$127&y;&-128>y;:;-1]}",xR,y):K("{(-1+\\@[&256;128+x;+;1])128+y}",xR,y))Az=an(tZ(xn-1),yn);I wz=zw,k[2];
  i(yn,Lv;S4(wy,v=yb,v=yh,v=yi,v=yl)*k=-1;k[1]=xn;S4(wx,,W(*k+1<k[1],Ii=*k+k[1]>>1;k[v<xh]=i),
                                                         W(*k+1<k[1],Ii=*k+k[1]>>1;k[v<xi]=i),
                                                         W(*k+1<k[1],Ii=*k+k[1]>>1;k[v<xl]=i))S4(wz,zb=*k,zh=*k,zi=*k,zl=*k))y(z))
 Yt(fir(binZ(x,enl(y))))YmMA(r2f(binZ,x,y))YD(x=x(cD(xR));binD(x,y))ed1(y))
SN A2(binD,/*01*/Q(xtD)YD(x=ofp(xR);x(binZ(x,ofp(y))))YZC(binD(x,N(cD(y))))Yt(fir(binD(x,enl(y))))YmMA(r2f(binD,x,y))ed1(y))
SN A2(bin,/*01*/ XZC(binZ(x,y))XD(binD(x,y))Xm(_1(xx,bin(xy,y)))et1(y))
AX(adv,Q(xtr)Ii=xE;x=xx;Ik=xK;Ay=*a;SW(i,
 CR(0,P(n==1,Xt(e1(x,y))bin(x,y))e8(x,a,n))
 CR(1,P(n==1,P(xtzZ||xtdD,dec(x,y))Xc(jc(xv,y))XC(jC(xV,xn,y))P(k<2,cf(x,y))f1(x,y))P(k<2,nwf(x,a,n))P(n-k==1,nwf(x,a,n))f8(x,a,n))
 CR(2,P(n==1,P(xtzZ||xtdD,enc(x,y))Xc(sc(xv,y))XC(sC(xV,xn,y))P(k<2,cs(x,y))s1(x,y))P(k<2,nws(x,a,n))P(n-k==1,nws(x,a,n))s8(x,a,n))
 CR(3,n==1?xtz?win(gl(x),y):p1(x,y):n==2?k==1?y(ste(x,y,a[1])):y(p2(x,y,a[1])):er8(a,n))
 CR(4,P(n==2,y(r2(x,y,a[1])))er8(a,n))
 CR(5,P(n==2,y(l2(x,y,a[1])))l8(x,a,n)))er8(a,n))
