name: Build and Test ubuntu

on:
  schedule:
  - cron:  "0 9 * * *"
  workflow_dispatch:

jobs:
  buildtestubuntu:
    name: Build and Test ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: upstream
      - name: make and test
        run: |
          make k
          make t
