name: Build and Test macos

on:
  push:
    branches: [upstream]
  workflow_dispatch:

jobs:
  buildtestmacos:
    name: Build and Test MacOS
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          ref: upstream
      - name: make and test
        run: |
          make k-libc
          mv k-libc k
          make t
